return {
  {
    "nvim-lua/plenary.nvim",
    lazy = true,
  },
  {
    -- 치트시트 전용 가상 플러그인 (plenary 팝업 활용)
    dir = vim.fn.stdpath("config"),
    name = "cheatsheet",
    lazy = true,
    keys = {
      { "<leader>?", desc = "치트시트 열기" },
    },
    config = function()
      vim.keymap.set("n", "<leader>?", function()
        local lines = {
          "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
          "  Nvim 치트시트                               j/k 스크롤  q 닫기",
          "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
          "",
          "  [이동]",
          "  H / L              줄 처음 / 줄 끝",
          "  J / K              다음 단락 / 이전 단락",
          "  gg / G             파일 처음 / 파일 끝",
          "  Ctrl+d / Ctrl+u    반 페이지 아래 / 위",
          "  n / N              다음/이전 검색 결과 (화면 중앙)",
          "  * / #              커서 단어 앞/역 검색 (화면 중앙)",
          "",
          "  [삽입 모드]",
          "  i / a              커서 앞 / 뒤 삽입",
          "  I / A              줄 맨 앞 / 끝 삽입",
          "  o / O              아래 / 위 새 줄 삽입",
          "  jk                 Normal 모드로",
          "  Ctrl+o             삽입 모드에서 명령 하나 실행",
          "",
          "  [검색 / 치환]",
          "  /word              파일 내 검색",
          "  <leader>fg         프로젝트 전체 grep",
          "  <leader>ff         파일명 검색",
          "  <leader>nh         검색 하이라이트 제거",
          "  :%s/old/new/g      전체 치환",
          "  :%s/old/new/gc     하나씩 확인하며 치환 (y/n/q)",
          "",
          "  [Visual / 편집]",
          "  Ctrl+v             Visual Block 시작",
          "  I / A              (Block) 각 줄 앞 / 끝 삽입",
          "  Ctrl+a             전체 선택",
          "  v + p              레지스터 보존 붙여넣기",
          "",
          "  [매크로]",
          "  qa                 a 레지스터 녹화 시작",
          "  q                  녹화 종료",
          "  @a / @@            매크로 실행 / 마지막 재실행",
          "  3@a                3번 반복 실행",
          "",
          "  [파일 / 저장]",
          "  <leader>fs         저장",
          "  <leader>fp         현재 파일 상대경로 복사",
          "  :let @+=expand('%:p')  전체 경로 복사",
          "",
          "  [버퍼]",
          "  Tab / S-Tab        다음 / 이전 버퍼",
          "  <leader>1~9        버퍼라인 n번째 버퍼로 이동",
          "  <leader>bb         직전 버퍼로 전환",
          "  <leader>bo         현재 버퍼 외 모두 닫기",
          "  <leader>br / bl    오른쪽 / 왼쪽 버퍼 모두 닫기",
          "  <leader>bx         모든 버퍼 닫기 (확인)",
          "",
          "  [LSP]",
          "  gd / gD            정의 / 타입 정의로 이동",
          "  gi                 구현으로 이동",
          "  gr                 참조 목록 (lspsaga 팝업, q로 닫기)",
          "  gh                 정의 미리보기 (peek)",
          "  <leader>lh         Hover 문서",
          "  <leader>lr         심볼 이름 변경",
          "  <leader>la         코드 액션",
          "  <leader>ld         진단 상세 보기",
          "  ]d / [d            다음 / 이전 진단",
          "  <leader>ll         Lint 실행",
          "",
          "  [리팩토링]",
          "  <leader>rv         변수로 추출 (visual)",
          "  <leader>re         함수로 추출 (visual)",
          "  <leader>ri         인라인 변수",
          "",
          "  [Git]",
          "  <leader>gg         Lazygit 열기",
          "",
          "  [테스트 (Neotest)]",
          "  <leader>tn         가장 가까운 테스트 실행",
          "  <leader>tf         현재 파일 전체 테스트",
          "  <leader>tl         마지막 테스트 재실행",
          "  <leader>td         가장 가까운 테스트 디버그",
          "  <leader>ts         테스트 요약 패널 토글",
          "  <leader>to         테스트 출력 보기",
          "  <leader>tp         테스트 출력 패널 토글",
          "  ]t / [t            다음 / 이전 실패한 테스트",
          "",
          "  [디버그 (DAP)]",
          "  F5 / <leader>dc    디버그 시작 / 계속",
          "  F9 / <leader>db    중단점 토글",
          "  <leader>dB         조건부 중단점",
          "  F10 / F11 / F12    Step Over / Into / Out",
          "  <leader>dq         디버그 종료",
          "  <leader>du         DAP UI 토글",
          "  <leader>de         표현식 평가",
          "  <leader>dm         현재 메서드 디버그 (Python)",
          "  <leader>dC         현재 클래스 디버그 (Python)",
          "",
          "  [AI 코드 완성]",
          "  Alt+y              제안 수락",
          "  Alt+[              제안 거절",
          "  Alt+n              다음 제안",
          "",
          "  [AI 채팅 (CodeCompanion)]",
          "  <leader>aa         AI 액션 팔레트",
          "  <leader>ac         AI 채팅 토글",
          "  <leader>as         선택 코드를 채팅에 추가 (visual)",
          "",
          "  [Python]",
          "  <leader>pym        모듈 경로 복사 (예: flywheel.strada.foo)",
          "",
          "  [기타]",
          "  <leader>ul         상대 줄 번호 토글",
          "  <leader>?          이 치트시트 열기",
          "",
          "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
        }

        local buf = vim.api.nvim_create_buf(false, true)
        vim.api.nvim_buf_set_lines(buf, 0, -1, false, lines)
        vim.bo[buf].modifiable = false
        vim.bo[buf].filetype = "markdown"

        local width = 74
        local max_height = vim.o.lines - 4
        local height = math.min(#lines, max_height)
        local win = vim.api.nvim_open_win(buf, true, {
          relative = "editor",
          width = width,
          height = height,
          row = math.floor((vim.o.lines - height) / 2),
          col = math.floor((vim.o.columns - width) / 2),
          style = "minimal",
          border = "rounded",
          title = " Cheatsheet ",
          title_pos = "center",
        })

        vim.keymap.set("n", "q", function()
          vim.api.nvim_win_close(win, true)
        end, { buffer = buf, nowait = true })
      end, { desc = "치트시트 열기" })
    end,
  },
}
